name: Check DCO

on:
  pull_request:

jobs:
  check-dco:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@416cafbc9c07f26219d09981d9ac49ce29b5bfea #v1.3.4
        with:
          exempt-authors: |
            austin@zieglers.ca
