name: Check DCO

on:
  pull_request:

jobs:
  check-dco:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@efa6164fb3608ab18f9b31d16d809ce177541ba4 #v1.3.3
        with:
          exempt-authors: |
            austin@zieglers.ca
