name: Check DCO

on:
  pull_request:

permissions: {}

jobs:
  check-dco:
    name: Check DCO Signature
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: KineticCafe/actions-dco@41ccac559c7150e0e9ffea00785fd173c473e2ee #v1.3.5
