name: Check DCO

on:
  pull_request:

jobs:
  check-dco:
    runs-on: ubuntu-latest
    steps:
      - uses: KineticCafe/actions-dco@a7f6488b8cadf38f423990df5fb9305dc33835ea #v1.3.2
        with:
          exempt-authors: |
            austin@zieglers.ca
